### ISSUE TITLE
Implementation Roadmap

### ISSUE THREAD

**Issue by 95th** [95th/ng_case#1]
Case study on Angular training (Plan View)
- [ ]	Registration
	- [ ]	User should be able to register himself/herself to the application
		- [ ]	First Name (Only Alphabets should be allowed)
		- [ ]	Last Name (Only Alphabets should be allowed)
		- [ ]	Date of Birth (Calendar field, should be greater than current date)
		- [ ]	Email address (domain name should be validated)
		- [ ]	Address Line 1
		- [ ]	Address Line 2
		- [ ]	City (Only Alphabets should be allowed)
		- [ ]	State (Only Alphabets should be allowed)
		- [ ]	Country (Only Alphabets should be allowed)
		- [ ]	Zip code (City should be validated against the Zip code)
		- [ ]	Username
		- [ ]	Password
		- [ ]	Re-enter password (for confirmation) 
	- [ ]	On successful registration, user should be redirected to dashboard
	- [ ]	Implement the ADA concepts and add some animations on registration page load
- [ ]	Login
	- [ ]	Forgot Password option needs to be provided
	- [ ]	On successful login, user should be redirected to dashboard
	- [ ]	If 3 unsuccessful logins, after that lock the user
- [ ]	(Admin) Dashboard
	- [ ]	Message Inbox
		- [ ]	Display message
	- [ ]	Display submitted timesheet from user
	- [ ]	List of users registered in the application should be listed
	- [ ]	Table should contain “Edit/View”, “Unlock” and “Delete” options against each user
	- [ ]	On click on the respective button, selected user should be edited/viewed/Unlock/deleted
	- [ ]	Redirect to login if not authorized
- [ ]	(Only Admin) Create work type
	- [ ]	Work type code
	- [ ]	Work type description
- [ ]	(Only Admin) Create work item
	- [ ]	Work item code
	- [ ]	Work item description
	- [ ]	Work type code (referential key to work type)
- [ ]	(Only Admin) User/work item assignment
	- [ ]	Select already created user
	- [ ]	List all work item
	- [ ]	Assign multiple work item to one user
	- [ ]	Save
- [ ]	(Admin/User) Send Message
	- [ ]	To User
	- [ ]	Subject (multiline)
	- [ ]	Send button
- [ ]	(Admin/User) Dashboard
	- [ ]	Redirect to login if not authorized
	- [ ]	Message Inbox
		- [ ]	Display message
	- [ ]	Assigned work item
		- [ ]	Display assign work item
- [ ]	User timesheet entry
	- [ ]	Timesheet entry in multiple rows having following columns
		- [ ]	Date (calendar)
		- [ ]	Work item (drop down/ list only assign work item)
		- [ ]	Hours
- [ ]	Application log & Reporting
	- [ ]	Capture all the Api calls with url/user details/timestamp
	- [ ]	Generate weekly report with the name ‘Usability Report’ with the details
		- [ ]	UserName
		- [ ]	ApiName
		- [ ]	Count (number of times user has accessed the url)
